version: '3.8'

services:
  app:
    image: seu_app_image
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://admin:preawbAu3NAWZkgpwdKrGpK4VZwEgCP2@dpg-cpgefq8l6cac73b9fu40-a/pdv_desktop_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: preawbAu3NAWZkgpwdKrGpK4VZwEgCP2